# Generated by Django 5.1 on 2025-12-08 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kudos',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Kudos'},
        ),
        migrations.AlterField(
            model_name='kudos',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_kudos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kudos',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_kudos', to=settings.AUTH_USER_MODEL),
        ),
    ]
