# Generated by Django 5.1 on 2026-01-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_kudos_recipient_alter_kudos_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kudos',
            name='recipient',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kudos',
            name='sender',
            field=models.IntegerField(),
        ),
    ]
