# Generated by Django 5.1 on 2026-01-24 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_kudos_recipient_alter_kudos_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kudos',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_kudos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kudos',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_kudos', to=settings.AUTH_USER_MODEL),
        ),
    ]
