# Generated by Django 5.1 on 2026-01-25 02:39

from django.db import migrations

def clean_invalid_foreign_keys(apps, schema_editor):
    Kudos = apps.get_model('yourappname', 'Kudos')          # ← change 'yourappname' to real app name, e.g. 'users'
    CustomUser = apps.get_model('yourappname', 'CustomUser')

    try:
        default_user = CustomUser.objects.get(id=1)         # ← change 1 to your real superuser/admin user ID
    except CustomUser.DoesNotExist:
        default_user = None                                 # or handle differently

    for kudos in Kudos.objects.all():
        fixed = False

        if kudos.sender_id and not CustomUser.objects.filter(id=kudos.sender_id).exists():
            kudos.sender = default_user
            fixed = True

        if kudos.recipient_id and not CustomUser.objects.filter(id=kudos.recipient_id).exists():
            kudos.recipient = default_user
            fixed = True

        if fixed:
            kudos.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_kudos_recipient_alter_kudos_sender'),
    ]

    operations = [
    ]
