# Generated by Django 5.1 on 2026-01-25 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20260125_1039'),
    ]

    operations = [
    ]
