# Generated by Django 5.1 on 2025-11-15 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pulse_logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pulselog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_pulses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pulselog',
            name='workload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse_logs.workload'),
        ),
    ]
