# Generated by Django 5.1 on 2025-11-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse_logs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulselog',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pulselog',
            name='timestamp_local',
            field=models.DateTimeField(null=True),
        ),
    ]
