# Generated by Django 5.1 on 2025-11-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse_logs', '0003_alter_pulselog_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulselog',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
