# Generated by Django 5.1 on 2025-11-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse_logs', '0004_alter_pulselog_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulselog',
            name='week_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pulselog',
            name='year',
            field=models.IntegerField(default=1900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pulselog',
            name='year_week',
            field=models.IntegerField(default=190000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pulselog',
            name='timestamp_local',
            field=models.DateTimeField(),
        ),
    ]
