# Generated by Django 5.1 on 2026-01-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0002_alter_userpoint_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
